server:
  port: 18800
  tomcat:
    uri-encoding: UTF-8
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true